# Generated by Django 2.2.6 on 2019-10-17 00:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('address', models.GenericIPAddressField(default='255.255.255.255', validators=[django.core.validators.validate_ipv4_address])),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('C', 'Critical'), ('D', 'Debug'), ('E', 'Error'), ('W', 'Warning'), ('I', 'Info')], max_length=20, null=True)),
                ('details', models.TextField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='api.Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='environment', to='api.Environment'),
        ),
    ]
