# Generated by Django 2.2.6 on 2019-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Undefined', max_length=150),
        ),
    ]
